version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
    target-branch: 'main'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'auto-update'
#    ignore:
#      - dependency-name: "express"
#        versions: [">=5.0.0"]
