spool vm_cd.log

  CREATE MATERIALIZED VIEW "CISADM"."CARTEIRA_DIARIA"
  TABLESPACE "CISTS_01"
  BUILD IMMEDIATE
  USING INDEX
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS
	SELECT  
			--BILL.BILL_ID,
			--BSEG.BSEG_ID,        
			--CASE WHEN BSEG.SA_ID IS NULL THEN FT.SA_ID ELSE BSEG.SA_ID END SAID,        
			TO_CHAR(BILL.BILL_DT, 'DD/MM/YYYY') DT_REFER, 
			MCM.CHAR_VAL MUC,        
			translate(replace(replace(replace(replace(replace(MCM.DESCR, ';', '/'),chr(10),' '),chr(13)),chr(9)),';''/'),' ÁÃÀÂÉÈÊËÍÌÎÏÓÕÒÔÖÚÙÛÜÇ¿#~',' AAAAEEEEIIIIOOOOOUUUUC') DESCCR_UC,
			PERNFIL.ENTITY_NAME FILIAL_VDA,        
			translate(replace(replace(replace(replace(replace(MAINNAME.ENTITY_NAME, ';', '/'),chr(10),' '),chr(13)),chr(9)),';''/'),' ÁÃÀÂÉÈÊËÍÌÎÏÓÕÒÔÖÚÙÛÜÇ¿#~',' AAAAEEEEIIIIOOOOOUUUUC') NM_CLI,
			'''' ||  APR.ACCT_ID || '''' COD_CLI,        
			'''' ||  PREMENTCHAR.adhoc_char_val || '''' COD_ENDER_ENTRG,
			'''' ||  PREMFATCHAR.adhoc_char_val || '''' COD_ENDER_FAT,
			'''' ||  PREMENTCHAR.adhoc_char_val || '''' LOC_ENTRG,
			'''' ||  PREMFATCHAR.adhoc_char_val || '''' LOC_FAT,
			translate(replace(replace(replace(replace(replace(PREMENT.ADDRESS2 || ' , ' || PREMENT.ADDRESS3 || ' , ' || PREMENT.ADDRESS4 , ';', '/'),chr(10),' '),chr(13)),chr(9)),';''/'),' ÁÃÀÂÉÈÊËÍÌÎÏÓÕÒÔÖÚÙÛÜÇ¿#~',' AAAAEEEEIIIIOOOOOUUUUC') ENDER_ENTRG,
			translate(replace(replace(replace(replace(replace(PREMFAT.ADDRESS2 || ' , ' || PREMFAT.ADDRESS3 || ' , ' || PREMFAT.ADDRESS4  , ';', '/'),chr(10),' '),chr(13)),chr(9)),';''/'),' ÁÃÀÂÉÈÊËÍÌÎÏÓÕÒÔÖÚÙÛÜÇ¿#~',' AAAAEEEEIIIIOOOOOUUUUC') ENDER_FAT,
			PHONECLI.CONTACT_VALUE FONE_CNTAT,
			'PRAZO 30DD' CONDC_PGTO,
			0 LIM_CREDT,
			case when trim(QUERYSVCTASK.GNF)  IS NOT NULL then '''' || QUERYSVCTASK.GNF || '''' else  null  end NUM_TITLO,
			1 PCELA_TITLO,      
			CASE 
				WHEN SA.SA_TYPE_CD IN ('G-RES', 'G-RES-B','CM-RD', 'CM-RD-B', 'CM-RC', 'CM-RC-B') THEN 'NFF'             
				ELSE 'AVISO DE DEBITO' 
			END CLASS_TITLO,
			CASE 
				WHEN SA.SA_TYPE_CD IN ('G-RES', 'G-RES-B','CM-RD', 'CM-RD-B', 'CM-RC', 'CM-RC-B') THEN 'NFF'         
				WHEN SA.SA_TYPE_CD IS NULL AND FT.FT_TYPE_FLG = 'AD' THEN 'CHEQUE'
				WHEN SA.SA_TYPE_CD IN ('PA-COM') THEN 'RENEGOCIACAO'           
			END TP_TITLO,       
			CASE 
				WHEN SA.SA_TYPE_CD IN ('G-RES', 'G-RES-B') THEN 'VD GLP CONS FINAL-MI'
				WHEN SA.SA_TYPE_CD IN ('CM-RD', 'CM-RD-B') THEN 'SRV TAXA COBRANCA-MI'
				WHEN SA.SA_TYPE_CD IN ('CM-RC', 'CM-RC-B') THEN 'SRV MANUTENCAO-MI'
				WHEN SA.SA_TYPE_CD IS NULL AND FT.FT_TYPE_FLG = 'AD' THEN 'AV DEB JUROS-MI'
				WHEN SA.SA_TYPE_CD IN ('PA-COM') AND SA.CIS_DIVISION = 'DIV1' THEN 'AV DEB UG-RENEGOC-MI' 
				WHEN SA.SA_TYPE_CD IN ('PA-COM') AND SA.CIS_DIVISION = 'DIV2' THEN 'AV DEB BA-RENEGOC-MI'      
			END TP_TRANS,
			CASE
				WHEN  QUERYEBTIDA.COUNT_BS > 0 AND QUERYEBTIDA.COUNT_BX = 0 THEN 'Y' 
				WHEN  QUERYEBTIDA.COUNT_BX > 0 AND QUERYEBTIDA.COUNT_BS = 0 THEN 'N' 
			END AFETA_EBITDA,
			'CARTEIRA-MI' MTODO_PGTO,
			NULL NUM_BCRIO,
			PREMFAT.CITY MUN_VDA,
			TO_CHAR (TO_DATE(SUBSTR(QUERYSVCTASK.DATAEMI,1,10), 'YYYY-MM-DD'), 'DD/MM/YYYY')  DT_EMIS,
			TO_CHAR (TO_DATE(SUBSTR(BILL.DUE_DT,1,10), 'YYYY-MM-DD'), 'DD/MM/YYYY') DT_VCTO,    
			NULL PRROG_PARA,
			(TRUNC(SYSDATE) - TO_DATE(SUBSTR(BILL.DUE_DT,1,10), 'YYYY-MM-DD')) DIA_ATRSO,
			FT.CUR_AMT VLR_TITLO,
			CASE 
				WHEN  QUERYVALPAGO.PAY_SEG_AMT IS NULL THEN           
				   NVL(FT.CUR_AMT,0)
				ELSE
				 NVL((QUERYVALPAGO.PAY_SEG_AMT - (QUERYVALPAGO.PAY_SEG_AMT -FT.CUR_AMT)-FT.CUR_AMT),0)
			END SDO_TITLO  ,    
			PERNCONSULTO.ENTITY_NAME VDDOR,
			'017' CANAL,
			NULL DADOS_EMITE, NULL MOTVO_DEVLC_CHEQ, NULL COBDR, NULL OCOR, NULL STTUS_JURID, NULL DT_JURID,
			NULL STTUS_PROTE, NULL DT_PROTE,
			CASE WHEN  BC.ADHOC_CHAR_VAL IS NOT NULL THEN 'PROVISIONADO' ELSE NULL END STTUS_PROVS,
			BC.ADHOC_CHAR_VAL DT_PROVS,
			NULL STTUS_PRROG, NULL HIST_PRROG,
			CASE WHEN NVL(QUERYRENEG.RK,'0')='0' THEN NULL ELSE 'RENEGOCIADO' END STTUS_RENEG,
			QUERYRENEG.RK HIST_RENEG,
			NULL NUM_NOTA_PROMS,
			QUERYRENEG.SAR NUM_CONTR_RENEG,
			NULL NUM_TITLO_ORIGN,
			NULL DT_VCTO_ORIGN,
			CASE WHEN  BC.ADHOC_CHAR_VAL IS NOT NULL THEN 'PROVISIONADO' ELSE NULL END ULT_STTUS,
			NULL DT_STTUS_COBR, 
			NULL STTUS_COBR, NULL COMEN, 
			'Medicao Individual' SGMTO_GERCIAL, 
			NULL TP_RLCTO,
			CASE WHEN NVL(QUERYRENEG.RK,'0')='0' THEN 'A Vista' ELSE 'Diferido' END CONDC_PGTO_CLI,
			NULL DT_CHMAD, NULL DT_PROMS, NULL VLR_PROMT, NULL DT_FOLLOW_UP, NULL OBS, 'Automatico' TP_CREDT, NULL TP_GARNT,          
			translate(replace(replace(replace(replace(replace(PERNCONSULTO.ENTITY_NAME , ';', '/'),chr(10),' '),chr(13)),chr(9)),';''/'),' ÁÃÀÂÉÈÊËÍÌÎÏÓÕÒÔÖÚÙÛÜÇ¿#~',' AAAAEEEEIIIIOOOOOUUUUC') VDDOR_CAD_CLI,        
			'Medicao Individual' CELA_COBR, NULL RESPSVL_CART,
			'''' || SUBSTR(FILEMI.PER_ID_NBR,1,2) || '''' COD_CIA,
			'''' || LPAD(SUBSTR(FILEMI.PER_ID_NBR,3,4),4,'0') || '''' COD_FILIAL,
			 '110' COD_SGMTO_GERCIAL, 'ULTRAGAZ' TP_COBR, 'CARTEIRA' TP_CART,
			--CASE WHEN QUERYPERDA.TOTAL > 0 THEN 'S' ELSE 'N' END PERDA,
			CASE WHEN BILL.DUE_DT < SYSDATE THEN 'VENCIDO' ELSE 'A VENCER' END STTUS,
			EMAILCLI.CONTACT_VALUE EMAIL,
			NULL JUROS_DE_PARCELA
		  --FT.* 
	FROM CI_FT FT 
	INNER JOIN CI_BILL BILL ON (BILL.BILL_ID = FT.BILL_ID OR BILL.BILL_ID = FT.PARENT_ID)
	LEFT JOIN CI_BSEG BSEG ON BSEG.BILL_ID = BILL.BILL_ID AND BSEG.SA_ID = FT.SA_ID AND FT.SIBLING_ID = BSEG.BSEG_ID
	LEFT JOIN CI_BSEG_CALC BSEGC ON BSEGC.BSEG_ID = BSEG.BSEG_ID 
	LEFT JOIN CI_SA SA ON SA.SA_ID = BSEG.SA_ID  
	LEFT JOIN CI_BILL_CHAR BC ON BC.BILL_ID = BILL.BILL_ID AND CHAR_TYPE_CD = 'CM-PDDSD' 
	INNER JOIN CI_ACCT ACCT ON ACCT.ACCT_ID = BILL.ACCT_ID
	JOIN CI_ACCT_PER APR ON ACCT.ACCT_ID = APR.ACCT_ID AND APR.ACCT_REL_TYPE_CD = 'MAIN' AND APR.MAIN_CUST_SW = 'Y'
	JOIN CI_PER_NAME MAINNAME ON MAINNAME.PER_ID = APR.PER_ID
	LEFT JOIN CI_ACCT_PER APC ON ACCT.ACCT_ID = APC.ACCT_ID AND APC.ACCT_REL_TYPE_CD = 'COND'
	LEFT JOIN CI_PER_PER FIL ON FIL.PER_ID1 = APC.PER_ID AND FIL.PER_REL_TYPE_CD = 'ABSTECED'
	LEFT JOIN CI_PER_PER EMIS ON EMIS.PER_ID1 = APC.PER_ID AND EMIS.PER_REL_TYPE_CD = 'EMISSORA'
	LEFT JOIN CI_PER_ID FILEMI ON FILEMI.PER_ID = EMIS.PER_ID2 AND FILEMI.ID_TYPE_CD ='CM-IDCCP'
	LEFT JOIN CI_PER_NAME PERNFIL ON PERNFIL.PER_ID = FIL.PER_ID2 AND PERNFIL.NAME_TYPE_FLG = 'PRIM' AND PERNFIL.PRIM_NAME_SW = 'Y'
	LEFT JOIN CI_PER_NAME PERNCLI ON PERNCLI.PER_ID = APR.PER_ID AND PERNCLI.NAME_TYPE_FLG = 'PRIM' AND PERNCLI.PRIM_NAME_SW = 'Y'
	LEFT JOIN CI_PER_PER PERCONSULTO ON PERCONSULTO.PER_ID1 = APC.PER_ID AND  PERCONSULTO.PER_REL_TYPE_CD = 'CONSULTO'
	LEFT JOIN CI_PER_NAME PERNCONSULTO ON PERNCONSULTO.PER_ID = PERCONSULTO.PER_ID2
	LEFT JOIN CI_PER_CHAR   PCH     ON PERCONSULTO.PER_ID2=PCH.PER_ID AND PCH.CHAR_TYPE_CD = 'CM-MCROM'
	LEFT JOIN CI_CHAR_VAL_L MCM ON PCH.CHAR_VAL = MCM.CHAR_VAL AND MCM.CHAR_TYPE_CD = 'CM-MCROM' AND MCM.LANGUAGE_CD = 'PTB'
	LEFT JOIN CI_SA SAENT ON SAENT.ACCT_ID = ACCT.ACCT_ID AND SAENT.SA_TYPE_CD IN ('G-RES','G-RES-B')
	LEFT JOIN CI_PREM PREMENT ON PREMENT.PREM_ID = SAENT.CHAR_PREM_ID
	LEFT JOIN ci_prem_char PREMENTCHAR on PREMENTCHAR.PREM_ID = PREMENT.PREM_ID and PREMENTCHAR.char_type_cd = 'CM-IDUC'
	LEFT JOIN CI_PREM PREMFAT ON PREMFAT.PREM_ID = ACCT.MAILING_PREM_ID
	LEFT JOIN ci_prem_char PREMFATCHAR on PREMFATCHAR.PREM_ID = PREMFAT.PREM_ID and PREMFATCHAR.char_type_cd = 'CM-IDUC'
	LEFT JOIN (
		   SELECT PER_ID, CONTACT_VALUE
		   FROM (
			   SELECT PER_ID, CONTACT_VALUE,
					  ROW_NUMBER() OVER (PARTITION BY PER_ID ORDER BY CONTACT_VALUE) AS RN
			   FROM C1_PER_CONTDET
			   WHERE COMM_RTE_TYPE_CD IN (
					   SELECT COMM_RTE_TYPE_CD 
					   FROM C1_COMM_RTE_TYPE 
					   WHERE COMM_RTE_METH_FLG in ('PHONE','CELLPHONE')
				   )
			   AND CONTACT_VALUE IS NOT NULL
		   ) SUBQUERY
		   WHERE RN = 1
	) PHONECLI ON PHONECLI.PER_ID = APR.PER_ID
	LEFT JOIN (
			SELECT 
				--SVC.* ,
				SVC.F1_SVC_TASK_ID,
				SVCTOBJ.PK_VALUE1 BSEG_ID, 
				CASE WHEN SVC.BUS_OBJ_CD IN ('CM-NotaFiscalGasTask') THEN 
					XMLTYPE(SVC.bo_data_area).EXTRACT('//GASNF_XML/gasNotaFiscal/infNFe/ide/nNF/text()').getStringVal() 
				ELSE
					XMLTYPE(SVC.bo_data_area).EXTRACT('//MRNF_XML/meterReadingNotaFiscal/loteRps/Numero/text()').getStringVal() 
				END GNF  , 
				CASE WHEN SVC.BUS_OBJ_CD IN ('CM-NotaFiscalGasTask') THEN 
					XMLTYPE(SVC.bo_data_area).EXTRACT('//GASNF_XML/gasNotaFiscal/infNFe/ide/nfSitua/text()').getStringVal() 
				ELSE
					XMLTYPE(SVC.bo_data_area).EXTRACT('//MRNF_XML/meterReadingNotaFiscal/loteRps/nfSitua/text()').getStringVal() 
				END GNFSITUA   ,  
				CASE WHEN SVC.BUS_OBJ_CD IN ('CM-NotaFiscalGasTask') THEN 
					XMLTYPE(SVC.bo_data_area).EXTRACT('//GASNF_XML/gasNotaFiscal/infNFe/ide/dhEmi/text()').getStringVal()
				ELSE
					XMLTYPE(SVC.bo_data_area).EXTRACT('//MRNF_XML/meterReadingNotaFiscal/loteRps/DataEmissao/text()').getStringVal() 
				END DATAEMI
			FROM F1_SVC_TASK_REL_OBJ SVCTOBJ 
			INNER JOIN F1_SVC_TASK SVC ON SVC.F1_SVC_TASK_ID = SVCTOBJ.F1_SVC_TASK_ID
			WHERE SVCTOBJ.MAINT_OBJ_CD = 'BILL SEG' AND SVC.BO_STATUS_CD = 'PROCESSED'
	) QUERYSVCTASK ON QUERYSVCTASK.BSEG_ID = BSEG.BSEG_ID
	LEFT JOIN (
		SELECT 
		BILL_ID,
		SUM(CASE WHEN FT_TYPE_FLG = 'BS' THEN 1 ELSE 0 END) AS COUNT_BS,
		SUM(CASE WHEN FT_TYPE_FLG = 'BX' THEN 1 ELSE 0 END) AS COUNT_BX
		FROM 
			CI_FT      
		GROUP BY BILL_ID    
	) QUERYEBTIDA ON QUERYEBTIDA.BILL_ID = BILL.BILL_ID
	LEFT JOIN (
		SELECT BILL_ID, SUM(CUR_AMT) CUR_AMT FROM (
			SELECT BILL_ID, CASE WHEN SUM(CUR_AMT) >= 0  THEN  SUM(CUR_AMT) ELSE 0 END  CUR_AMT  FROM (
					SELECT 
						SUM(FT.CUR_AMT) AS CUR_AMT,
						B.BILL_ID 
					FROM
						CI_BILL B,
						CI_BSEG BS,
						CI_SA SA,
						CI_FT FT
					WHERE                                                
						B.BILL_ID = BS.BILL_ID
						AND BS.BSEG_ID = FT.SIBLING_ID
						AND FT.FREEZE_SW = 'Y'
						AND FT_TYPE_FLG = 'BS'
						AND NOT EXISTS (SELECT 'X'
										FROM   CI_FT FT2
										WHERE  FT2.SIBLING_ID = FT.SIBLING_ID
											AND FT2.FT_TYPE_FLG = 'BX')
						AND BS.SA_ID = SA.SA_ID
						GROUP BY FT.CUR_AMT, B.BILL_ID 
					UNION 
					SELECT SUM(FT.CUR_AMT) CUR_AMT , FT.BILL_ID                              
					FROM CI_FT FT
					INNER JOIN  CI_ADJ_TYPE_L ATL ON ATL.ADJ_TYPE_CD = FT.PARENT_ID AND ATL.LANGUAGE_CD = 'PTB' 
							AND ATL.ADJ_TYPE_CD  NOT IN ('DPA-FIX', 'XFER-OI', 'XFER', 'CMNGAMT', 'CM-DSCOM', 'LEITURA','CONNECT')
					INNER JOIN CI_BSEG BS ON FT.BILL_ID = BS.BILL_ID  AND BS.BSEG_STAT_FLG = 50  AND FT.SA_ID = BS.SA_ID   
					INNER JOIN CI_BILL PARENTBILL ON  PARENTBILL.BILL_ID = BS.BILL_ID
					LEFT JOIN CI_ADJ ADJ ON ADJ.ADJ_ID = FT.SIBLING_ID AND ADJ.ADJ_TYPE_CD = 'CM-DESCO'
					LEFT JOIN CI_ADJ_CHAR ADJCHAR ON ADJCHAR.ADJ_ID = FT.SIBLING_ID  AND ADJCHAR.CHAR_TYPE_CD = 'UG-BILL'
					LEFT JOIN CI_BILL BILL ON BILL.BILL_ID = ADJCHAR.CHAR_VAL_FK1                                           
					WHERE  FT.FT_TYPE_FLG = 'AD' AND SHOW_ON_BILL_SW = 'Y' 
						GROUP BY FT.CUR_AMT, FT.BILL_ID 
					UNION
						SELECT SUM(FT.CUR_AMT) CUR_AMT  , FT.BILL_ID                             
						FROM CI_FT FT
						INNER JOIN  CI_ADJ_TYPE_L ATL ON ATL.ADJ_TYPE_CD = FT.PARENT_ID AND ATL.LANGUAGE_CD = 'PTB' 
								AND ATL.ADJ_TYPE_CD  IN ('CMNGAMT', 'CM-DSCOM')
						INNER JOIN CI_BSEG BS ON FT.BILL_ID = BS.BILL_ID  AND BS.BSEG_STAT_FLG = 50  AND FT.SA_ID = BS.SA_ID   
						INNER JOIN CI_BILL PARENTBILL ON  PARENTBILL.BILL_ID = BS.BILL_ID
						LEFT JOIN CI_ADJ ADJ ON ADJ.ADJ_ID = FT.SIBLING_ID AND ADJ.ADJ_TYPE_CD = 'CM-DESCO'
						LEFT JOIN CI_ADJ_CHAR ADJCHAR ON ADJCHAR.ADJ_ID = FT.SIBLING_ID  AND ADJCHAR.CHAR_TYPE_CD = 'UG-BILL'
						LEFT JOIN CI_BILL BILL ON BILL.BILL_ID = ADJCHAR.CHAR_VAL_FK1                                           
						WHERE FT.FT_TYPE_FLG = 'AD' AND SHOW_ON_BILL_SW = 'Y' 
						GROUP BY FT.CUR_AMT, FT.BILL_ID 
					UNION
						SELECT  
							SUBQ.CUR_AMT CUR_AMT, BILL.BILL_ID 
						FROM
								CI_BILL BILL
						INNER JOIN CI_SA  SA ON SA.ACCT_ID = BILL.ACCT_ID AND SA.SA_TYPE_CD IN ( 'EXCSCRED' )
						INNER JOIN CI_SA_TYPE_L SAL ON SAL.SA_TYPE_CD = SA.SA_TYPE_CD AND SAL.LANGUAGE_CD = 'PTB'
															AND SAL.CIS_DIVISION = SA.CIS_DIVISION
						JOIN (
								SELECT
									BS.BILL_ID,
									SUM(FT_P.CUR_AMT) CUR_AMT
								FROM
											CI_BSEG BS
									JOIN CI_FT        FT ON FT.SIBLING_ID = BS.BSEG_ID
									JOIN CI_MATCH_EVT ME ON ME.MATCH_EVT_ID = FT.MATCH_EVT_ID
									LEFT JOIN CI_FT        FT_P ON FT_P.MATCH_EVT_ID = ME.MATCH_EVT_ID
															AND FT_P.FT_TYPE_FLG IN ( 'AD' )
															AND FT.SA_ID = FT_P.SA_ID
								GROUP BY
									BS.BILL_ID
							)    SUBQ ON SUBQ.BILL_ID = BILL.BILL_ID
						WHERE
						SUBQ.CUR_AMT IS NOT NULL                                               
				) GROUP BY BILL_ID, CUR_AMT
		 )  
		 GROUP BY BILL_ID
	) QUERYVALOR ON QUERYVALOR.BILL_ID = BILL.BILL_ID
	LEFT JOIN ( SELECT BS.BILL_ID, SAR, RK FROM CI_BSEG BS
					JOIN ( SELECT SA_ID SAR, COUNT(*) || ' '|| 'RENEGOCIADO' RK FROM CI_SA_CHAR WHERE CHAR_TYPE_CD = 'CM-BKPAC' AND CHAR_VAL='RENEGOTIATION' GROUP BY SA_ID)
				QK ON QK.SAR = BS.SA_ID
	)  QUERYRENEG ON QUERYRENEG.BILL_ID  = BILL.BILL_ID
	LEFT JOIN (
		   SELECT PER_ID, CONTACT_VALUE
		   FROM (
			   SELECT PER_ID, CONTACT_VALUE,
					  ROW_NUMBER() OVER (PARTITION BY PER_ID ORDER BY CONTACT_VALUE) AS RN
			   FROM C1_PER_CONTDET
			   WHERE COMM_RTE_TYPE_CD IN (
					   SELECT COMM_RTE_TYPE_CD
					   FROM C1_COMM_RTE_TYPE 
					   WHERE COMM_RTE_METH_FLG IN ('EMAIL')
				   )
			   AND CONTACT_VALUE IS NOT NULL
		   ) SUBQUERY
		   WHERE RN = 1
	) EMAILCLI ON EMAILCLI.PER_ID = APR.PER_ID
	LEFT JOIN (
		SELECT COUNT(FT.FT_ID) TOTAL, FT.BILL_ID, BS.BSEG_ID                              
		FROM CI_FT FT               
		INNER JOIN CI_BSEG BS ON FT.BILL_ID = BS.BILL_ID  AND BS.BSEG_STAT_FLG = 50  AND FT.SA_ID = BS.SA_ID   
		INNER JOIN CI_BILL PARENTBILL ON  PARENTBILL.BILL_ID = BS.BILL_ID
		LEFT JOIN CI_ADJ ADJ ON ADJ.ADJ_ID = FT.SIBLING_ID AND ADJ.ADJ_TYPE_CD = 'CMLOSSWO'
		LEFT JOIN CI_ADJ_CHAR ADJCHAR ON ADJCHAR.ADJ_ID = FT.SIBLING_ID  AND ADJCHAR.CHAR_TYPE_CD = 'UG-BILL'
		LEFT JOIN CI_BILL BILL ON BILL.BILL_ID = ADJCHAR.CHAR_VAL_FK1                                           
		WHERE  FT.FT_TYPE_FLG = 'AD' AND SHOW_ON_BILL_SW = 'Y' 
		GROUP BY FT.BILL_ID , BS.BSEG_ID   
	) QUERYPERDA ON QUERYPERDA.BSEG_ID = BSEG.BSEG_ID AND QUERYPERDA.BILL_ID = BILL.BILL_ID
	LEFT JOIN (
		 select BILL_ID,sa_id , sum(cur_amt) VAL from ci_ft where  ft_type_flg in ('BS', 'AD') 
		 GROUP BY BILL_ID,sa_id
	) QUERYSDO ON QUERYSDO.bill_id = BILL.BILL_ID AND QUERYSDO.SA_ID =  ft.sa_id 
	LEFT JOIN (     
		select 
			 (CUR_AMT*-1) PAY_SEG_AMT,
			 match_evt_id,
			 SA_ID
		from ci_ft 
		where  ft_type_flg = 'PS'
	) QUERYVALPAGO ON QUERYVALPAGO.MATCH_EVT_ID = FT.MATCH_EVT_ID AND QUERYVALPAGO.MATCH_EVT_ID  IS NOT NULL AND (QUERYVALPAGO.sa_id = SA.SA_ID OR QUERYVALPAGO.sa_id  = ft.sa_id ) 
	WHERE  FT.CUR_AMT > 0 
	AND 
		(
			CASE WHEN QUERYVALPAGO.PAY_SEG_AMT IS NOT NULL THEN
				(QUERYVALPAGO.PAY_SEG_AMT - (QUERYVALPAGO.PAY_SEG_AMT -FT.CUR_AMT)-FT.CUR_AMT) 
			ELSE 
				FT.CUR_AMT
			END    
		) > 0 
	--and FT.BILL_ID   = '586115582123' 
	ORDER BY 1;

   COMMENT ON MATERIALIZED VIEW "CISADM"."CARTEIRA_DIARIA"  IS 'snapshot table for snapshot CISADM.CARTEIRA_DIARIA';

spool off
