# .github/actions/setup-aws/action.yml
name: Setup AWS Credentials
description: Configura credenciais AWS
runs:
  using: 'composite'
  steps:
    - name: Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
